name = "FVUnraveling"
uuid = "eb1d51a1-ef5c-4e31-87b7-048ef0f46ab6"
authors = ["Malte Krug <malte.krug@uni-ulm.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BaryRational = "91aaffc3-5777-4842-85b7-5d3d5d6a3494"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Arpack = "0.5.4"
BaryRational = "1.1.1"
LinearAlgebra = "1.11.0"
SparseArrays = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
