name = "FVUnraveling"
uuid = "eb1d51a1-ef5c-4e31-87b7-048ef0f46ab6"
authors = ["Malte Krug <malte.krug@uni-ulm.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
